apiVersion: apps/v1
kind: Deployment
metadata:
  name: cust-recommendation-app
  labels:
    app: cust-recommendation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cust-recommendation-app
  template:
    metadata:
      labels:
        app: cust-recommendation-app
    spec:
      containers:
        - name: recommendation-app
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: cust-recommendation-service-cip
spec:
  selector:
    app: cust-recommendation-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      # nodePort: 30000
